#!/usr/bin/env bash

configdir="${XDG_CONFIG_HOME-$HOME/.config}/sway"
scriptdir="$configdir/scripts"

if [[ -e ~/.env ]]
then
	set -a
	source ~/.env
	set +a
fi

$scriptdir/exec-once /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

eval $(gnome-keyring-daemon --start -components=pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL
export SSH_AUTH_SOCK

sway
