#!/usr/bin/env bash
## Start wlsunset with coordinates from Geoclue

temp=$(mktemp)
where-am-i > "$temp" &

geoclue_done=0
while [[ $geoclue_done != 1 ]]
do
    cat "$temp" |
        awk '
            /^Latitude:/ {
                a = 1;
                next
            }
            a && /^Longitude:/ {
                b = 1
            }
            END {
                exit !b
            }' && geoclue_done=1
    sleep 1
done

kill %%

lat=$(cat "$temp" |
    awk '
        /Latitude:/ {
            printf "%.4s", $2;
            exit
        }')

long=$(cat "$temp" |
    awk '
        /Longitude:/ {
            printf "%.4s", $2;
            exit
        }')

rm "$temp"

processes=$(pgrep -U $(id -u) wlsunset)
if [[ -n "$processes" ]]
then
    kill $processes
fi

wlsunset -l $lat -L $long
